const browserGlobals = Object.fromEntries(
  [
    "window",
    "document",
    "navigator",
    "Node",
    "Element",
    "HTMLElement",
    "HTMLInputElement",
    "HTMLButtonElement",
    "HTMLDivElement",
    "ShadowRoot",
    "MutationObserver",
    "ResizeObserver",
    "IntersectionObserver",
    "Worker",
    "OffscreenCanvas",
    "ImageBitmap",
    "ImageData",
    "CanvasRenderingContext2D",
    "CSSStyleSheet",
    "AbortController",
    "AbortSignal",
    "DOMException",
    "getComputedStyle",
    "matchMedia",
    "innerWidth",
    "innerHeight",
    "crypto",
    "performance",
    "createImageBitmap",
    "atob",
    "btoa",
    "queueMicrotask",
    "setTimeout",
    "clearTimeout",
    "setInterval",
    "clearInterval",
    "requestAnimationFrame",
    "cancelAnimationFrame",
    "location",
    "self",
    "console",
    "Event",
    "MouseEvent",
    "KeyboardEvent",
    "CustomEvent",
    "TextDecoder",
    "TextEncoder",
    "structuredClone",
    "postMessage",
    "URL",
    "Blob",
  ].map((name) => [name, "readonly"]),
);
export default [
  {
    files: ["src/renderer/**/*.js", "src/core/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...browserGlobals, onmessage: "writable" },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];
